#ifndef DESKTOP_PP_PP_2020_AUTUMN_INFORMATICS_MODULES_TASK_1_LUCKYANCHENCKO_I_INTEGRAL_RECTANGLE_INTEGRAL_H_
#define DESKTOP_PP_PP_2020_AUTUMN_INFORMATICS_MODULES_TASK_1_LUCKYANCHENCKO_I_INTEGRAL_RECTANGLE_INTEGRAL_H_
// Copyright 2020 Luckianchencko Ivan

float get_Paral_Integral(float(*func)(float), int a, int b);
float func1(float x);
float func2(float x);
float func3(float x);

#endif  // DESKTOP_PP_PP_2020_AUTUMN_INFORMATICS_MODULES_TASK_1_LUCKYANCHENCKO_I_INTEGRAL_RECTANGLE_INTEGRAL_H_
